<<<<<<< HEAD
# state.py

from typing import TypedDict, List, Optional

class GradeOpsState(TypedDict):
    # Inputs
    student_id: str 
    question_text: str
    marking_scheme_text: Optional[str]
    transcription: str          # From OCR engine

    # Generated by Rubric Factory
    rubric: dict                # Output from rubric_factory.py

    # Final Output from Grader
    proposed_score: float
    justification: str          # Reasoning trace
    needs_review: bool          # Confidence based escalation flag
    error_axes: List[str]       # computational, conceptual, notation, presentation

    # Verification (Phase 3)
    verification_passed: Optional[bool]
=======
# state.py

from typing import TypedDict, List, Optional

class GradeOpsState(TypedDict):
    # Inputs
    student_id: str 
    question_text: str
    marking_scheme_text: Optional[str]
    transcription: str          # From OCR engine

    # Generated by Rubric Factory
    rubric: dict                # Output from rubric_factory.py

    # Final Output from Grader
    proposed_score: float
    justification: str          # Reasoning trace
    needs_review: bool          # Confidence based escalation flag
    error_axes: List[str]       # computational, conceptual, notation, presentation

    # Verification (Phase 3)
    verification_passed: Optional[bool]
>>>>>>> 15b1898f1ea7244db1b396e1e9d47837e0f8d22b
    verification_feedback: Optional[str]