

from typing import TypedDict, List, Optional

class GradeOpsState(TypedDict):
    # Inputs
    student_id: str 
    question_text: str
    marking_scheme_text: Optional[str]
    transcription: str          # From OCR engine

    # Generated by Rubric Factory
    rubric: dict                # Output from rubric_factory.py

    # Final Output from Grader
    proposed_score: float
    justification: str          # Reasoning trace
    needs_review: bool          # Confidence based escalation flag
    error_axes: List[str]       # computational, conceptual, notation, presentation
